#!/bin/bash
script=`dirname \`realpath $0\``
g++ -std=c++11 -Wall $script/../main.cpp -o $script/bsl-compiler &&
$script/bsl-compiler $1 >$1.cpp &&
g++ -std=c++11 -O3 $1.cpp -o $1.out &&
$1.out
rm $script/bsl-compiler 2>/dev/null &&
rm $1.cpp 2>/dev/null&&
rm $1.out 2>/dev/null

