#!/bin/bash
script=`dirname \`realpath $0\``
g++ -std=c++11 -Wall $script/../main.cpp -o $script/bsl-compiler &&
($script/bsl-compiler $1 >$1.cpp; rm $script/bsl-compiler) &&
(g++ -std=c++11 -O3 $1.cpp -o $1.out; rm $1.cpp) &&
($1.out; rm $1.out)

