#include <bsl_rt.h>
typedef struct { enum { BSL_TAG_False, BSL_TAG_True } T; } BSL_TYPE_Bool;
BSL_RT_VAR_T BSL_CON_False() {
  BSL_TYPE_Bool *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_Bool));
  BSL_VAR__1->T = BSL_TAG_False;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_True() {
  BSL_TYPE_Bool *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_Bool));
  BSL_VAR__1->T = BSL_TAG_True;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
typedef struct { enum { BSL_TAG_I, BSL_TAG_B, BSL_TAG_Add, BSL_TAG_Mul, BSL_TAG_Eq, BSL_TAG_If } T; BSL_RT_VAR_T arg0; BSL_RT_VAR_T arg1; BSL_RT_VAR_T arg2; } BSL_TYPE_Expr;
BSL_RT_VAR_T BSL_CON_I(BSL_RT_VAR_T BSL_VAR_arg0) {
  BSL_TYPE_Expr *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_Expr));
  BSL_VAR__1->T = BSL_TAG_I;
  BSL_VAR__1->arg0 = BSL_VAR_arg0;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_B(BSL_RT_VAR_T BSL_VAR_arg0) {
  BSL_TYPE_Expr *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_Expr));
  BSL_VAR__1->T = BSL_TAG_B;
  BSL_VAR__1->arg0 = BSL_VAR_arg0;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_Add(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1) {
  BSL_TYPE_Expr *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_Expr));
  BSL_VAR__1->T = BSL_TAG_Add;
  BSL_VAR__1->arg0 = BSL_VAR_arg0;
  BSL_VAR__1->arg1 = BSL_VAR_arg1;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_Mul(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1) {
  BSL_TYPE_Expr *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_Expr));
  BSL_VAR__1->T = BSL_TAG_Mul;
  BSL_VAR__1->arg0 = BSL_VAR_arg0;
  BSL_VAR__1->arg1 = BSL_VAR_arg1;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_Eq(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1) {
  BSL_TYPE_Expr *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_Expr));
  BSL_VAR__1->T = BSL_TAG_Eq;
  BSL_VAR__1->arg0 = BSL_VAR_arg0;
  BSL_VAR__1->arg1 = BSL_VAR_arg1;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_If(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_VAR_arg2) {
  BSL_TYPE_Expr *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_Expr));
  BSL_VAR__1->T = BSL_TAG_If;
  BSL_VAR__1->arg0 = BSL_VAR_arg0;
  BSL_VAR__1->arg1 = BSL_VAR_arg1;
  BSL_VAR__1->arg2 = BSL_VAR_arg2;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
typedef struct { enum { BSL_TAG_Pure, BSL_TAG_Free } T; BSL_RT_VAR_T arg0; } BSL_TYPE_IO;
BSL_RT_VAR_T BSL_CON_Pure(BSL_RT_VAR_T BSL_VAR_arg0) {
  BSL_TYPE_IO *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_IO));
  BSL_VAR__1->T = BSL_TAG_Pure;
  BSL_VAR__1->arg0 = BSL_VAR_arg0;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_Free(BSL_RT_VAR_T BSL_VAR_arg0) {
  BSL_TYPE_IO *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_IO));
  BSL_VAR__1->T = BSL_TAG_Free;
  BSL_VAR__1->arg0 = BSL_VAR_arg0;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
typedef struct { enum { BSL_TAG_Read, BSL_TAG_Write } T; BSL_RT_VAR_T arg0; BSL_RT_VAR_T arg1; } BSL_TYPE_IOImpl;
BSL_RT_VAR_T BSL_CON_Read(BSL_RT_VAR_T BSL_VAR_arg0) {
  BSL_TYPE_IOImpl *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_IOImpl));
  BSL_VAR__1->T = BSL_TAG_Read;
  BSL_VAR__1->arg0 = BSL_VAR_arg0;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_Write(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1) {
  BSL_TYPE_IOImpl *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_IOImpl));
  BSL_VAR__1->T = BSL_TAG_Write;
  BSL_VAR__1->arg0 = BSL_VAR_arg0;
  BSL_VAR__1->arg1 = BSL_VAR_arg1;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
typedef struct { enum { BSL_TAG_Nil, BSL_TAG_Cons } T; BSL_RT_VAR_T arg0; BSL_RT_VAR_T arg1; } BSL_TYPE_List;
BSL_RT_VAR_T BSL_CON_Nil() {
  BSL_TYPE_List *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_List));
  BSL_VAR__1->T = BSL_TAG_Nil;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_Cons(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1) {
  BSL_TYPE_List *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_List));
  BSL_VAR__1->T = BSL_TAG_Cons;
  BSL_VAR__1->arg0 = BSL_VAR_arg0;
  BSL_VAR__1->arg1 = BSL_VAR_arg1;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
typedef struct { enum { BSL_TAG_Just, BSL_TAG_Nothing } T; BSL_RT_VAR_T arg0; } BSL_TYPE_Maybe;
BSL_RT_VAR_T BSL_CON_Just(BSL_RT_VAR_T BSL_VAR_arg0) {
  BSL_TYPE_Maybe *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_Maybe));
  BSL_VAR__1->T = BSL_TAG_Just;
  BSL_VAR__1->arg0 = BSL_VAR_arg0;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_Nothing() {
  BSL_TYPE_Maybe *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_Maybe));
  BSL_VAR__1->T = BSL_TAG_Nothing;
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
typedef struct { } BSL_TYPE_Unit;
BSL_RT_VAR_T BSL_CON_Unit() {
  BSL_TYPE_Unit *BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_TYPE_Unit));
  return (BSL_RT_VAR_T)BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_0(BSL_RT_FUN_T fun) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 0 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_1(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 1 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_2(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 2 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  BSL_VAR__1->env[1] = BSL_VAR_arg1;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_3(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_VAR_arg2) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 3 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  BSL_VAR__1->env[1] = BSL_VAR_arg1;
  BSL_VAR__1->env[2] = BSL_VAR_arg2;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_4(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_VAR_arg2, BSL_RT_VAR_T BSL_VAR_arg3) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 4 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  BSL_VAR__1->env[1] = BSL_VAR_arg1;
  BSL_VAR__1->env[2] = BSL_VAR_arg2;
  BSL_VAR__1->env[3] = BSL_VAR_arg3;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_5(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_VAR_arg2, BSL_RT_VAR_T BSL_VAR_arg3, BSL_RT_VAR_T BSL_VAR_arg4) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 5 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  BSL_VAR__1->env[1] = BSL_VAR_arg1;
  BSL_VAR__1->env[2] = BSL_VAR_arg2;
  BSL_VAR__1->env[3] = BSL_VAR_arg3;
  BSL_VAR__1->env[4] = BSL_VAR_arg4;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_6(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_VAR_arg2, BSL_RT_VAR_T BSL_VAR_arg3, BSL_RT_VAR_T BSL_VAR_arg4, BSL_RT_VAR_T BSL_VAR_arg5) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 6 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  BSL_VAR__1->env[1] = BSL_VAR_arg1;
  BSL_VAR__1->env[2] = BSL_VAR_arg2;
  BSL_VAR__1->env[3] = BSL_VAR_arg3;
  BSL_VAR__1->env[4] = BSL_VAR_arg4;
  BSL_VAR__1->env[5] = BSL_VAR_arg5;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_7(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_VAR_arg2, BSL_RT_VAR_T BSL_VAR_arg3, BSL_RT_VAR_T BSL_VAR_arg4, BSL_RT_VAR_T BSL_VAR_arg5, BSL_RT_VAR_T BSL_VAR_arg6) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 7 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  BSL_VAR__1->env[1] = BSL_VAR_arg1;
  BSL_VAR__1->env[2] = BSL_VAR_arg2;
  BSL_VAR__1->env[3] = BSL_VAR_arg3;
  BSL_VAR__1->env[4] = BSL_VAR_arg4;
  BSL_VAR__1->env[5] = BSL_VAR_arg5;
  BSL_VAR__1->env[6] = BSL_VAR_arg6;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_8(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_VAR_arg2, BSL_RT_VAR_T BSL_VAR_arg3, BSL_RT_VAR_T BSL_VAR_arg4, BSL_RT_VAR_T BSL_VAR_arg5, BSL_RT_VAR_T BSL_VAR_arg6, BSL_RT_VAR_T BSL_VAR_arg7) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 8 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  BSL_VAR__1->env[1] = BSL_VAR_arg1;
  BSL_VAR__1->env[2] = BSL_VAR_arg2;
  BSL_VAR__1->env[3] = BSL_VAR_arg3;
  BSL_VAR__1->env[4] = BSL_VAR_arg4;
  BSL_VAR__1->env[5] = BSL_VAR_arg5;
  BSL_VAR__1->env[6] = BSL_VAR_arg6;
  BSL_VAR__1->env[7] = BSL_VAR_arg7;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_9(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_VAR_arg2, BSL_RT_VAR_T BSL_VAR_arg3, BSL_RT_VAR_T BSL_VAR_arg4, BSL_RT_VAR_T BSL_VAR_arg5, BSL_RT_VAR_T BSL_VAR_arg6, BSL_RT_VAR_T BSL_VAR_arg7, BSL_RT_VAR_T BSL_VAR_arg8) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 9 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  BSL_VAR__1->env[1] = BSL_VAR_arg1;
  BSL_VAR__1->env[2] = BSL_VAR_arg2;
  BSL_VAR__1->env[3] = BSL_VAR_arg3;
  BSL_VAR__1->env[4] = BSL_VAR_arg4;
  BSL_VAR__1->env[5] = BSL_VAR_arg5;
  BSL_VAR__1->env[6] = BSL_VAR_arg6;
  BSL_VAR__1->env[7] = BSL_VAR_arg7;
  BSL_VAR__1->env[8] = BSL_VAR_arg8;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_10(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_VAR_arg2, BSL_RT_VAR_T BSL_VAR_arg3, BSL_RT_VAR_T BSL_VAR_arg4, BSL_RT_VAR_T BSL_VAR_arg5, BSL_RT_VAR_T BSL_VAR_arg6, BSL_RT_VAR_T BSL_VAR_arg7, BSL_RT_VAR_T BSL_VAR_arg8, BSL_RT_VAR_T BSL_VAR_arg9) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 10 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  BSL_VAR__1->env[1] = BSL_VAR_arg1;
  BSL_VAR__1->env[2] = BSL_VAR_arg2;
  BSL_VAR__1->env[3] = BSL_VAR_arg3;
  BSL_VAR__1->env[4] = BSL_VAR_arg4;
  BSL_VAR__1->env[5] = BSL_VAR_arg5;
  BSL_VAR__1->env[6] = BSL_VAR_arg6;
  BSL_VAR__1->env[7] = BSL_VAR_arg7;
  BSL_VAR__1->env[8] = BSL_VAR_arg8;
  BSL_VAR__1->env[9] = BSL_VAR_arg9;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_11(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_VAR_arg2, BSL_RT_VAR_T BSL_VAR_arg3, BSL_RT_VAR_T BSL_VAR_arg4, BSL_RT_VAR_T BSL_VAR_arg5, BSL_RT_VAR_T BSL_VAR_arg6, BSL_RT_VAR_T BSL_VAR_arg7, BSL_RT_VAR_T BSL_VAR_arg8, BSL_RT_VAR_T BSL_VAR_arg9, BSL_RT_VAR_T BSL_VAR_arg10) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 11 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  BSL_VAR__1->env[1] = BSL_VAR_arg1;
  BSL_VAR__1->env[2] = BSL_VAR_arg2;
  BSL_VAR__1->env[3] = BSL_VAR_arg3;
  BSL_VAR__1->env[4] = BSL_VAR_arg4;
  BSL_VAR__1->env[5] = BSL_VAR_arg5;
  BSL_VAR__1->env[6] = BSL_VAR_arg6;
  BSL_VAR__1->env[7] = BSL_VAR_arg7;
  BSL_VAR__1->env[8] = BSL_VAR_arg8;
  BSL_VAR__1->env[9] = BSL_VAR_arg9;
  BSL_VAR__1->env[10] = BSL_VAR_arg10;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_12(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_VAR_arg2, BSL_RT_VAR_T BSL_VAR_arg3, BSL_RT_VAR_T BSL_VAR_arg4, BSL_RT_VAR_T BSL_VAR_arg5, BSL_RT_VAR_T BSL_VAR_arg6, BSL_RT_VAR_T BSL_VAR_arg7, BSL_RT_VAR_T BSL_VAR_arg8, BSL_RT_VAR_T BSL_VAR_arg9, BSL_RT_VAR_T BSL_VAR_arg10, BSL_RT_VAR_T BSL_VAR_arg11) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 12 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  BSL_VAR__1->env[1] = BSL_VAR_arg1;
  BSL_VAR__1->env[2] = BSL_VAR_arg2;
  BSL_VAR__1->env[3] = BSL_VAR_arg3;
  BSL_VAR__1->env[4] = BSL_VAR_arg4;
  BSL_VAR__1->env[5] = BSL_VAR_arg5;
  BSL_VAR__1->env[6] = BSL_VAR_arg6;
  BSL_VAR__1->env[7] = BSL_VAR_arg7;
  BSL_VAR__1->env[8] = BSL_VAR_arg8;
  BSL_VAR__1->env[9] = BSL_VAR_arg9;
  BSL_VAR__1->env[10] = BSL_VAR_arg10;
  BSL_VAR__1->env[11] = BSL_VAR_arg11;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_13(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_VAR_arg2, BSL_RT_VAR_T BSL_VAR_arg3, BSL_RT_VAR_T BSL_VAR_arg4, BSL_RT_VAR_T BSL_VAR_arg5, BSL_RT_VAR_T BSL_VAR_arg6, BSL_RT_VAR_T BSL_VAR_arg7, BSL_RT_VAR_T BSL_VAR_arg8, BSL_RT_VAR_T BSL_VAR_arg9, BSL_RT_VAR_T BSL_VAR_arg10, BSL_RT_VAR_T BSL_VAR_arg11, BSL_RT_VAR_T BSL_VAR_arg12) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 13 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  BSL_VAR__1->env[1] = BSL_VAR_arg1;
  BSL_VAR__1->env[2] = BSL_VAR_arg2;
  BSL_VAR__1->env[3] = BSL_VAR_arg3;
  BSL_VAR__1->env[4] = BSL_VAR_arg4;
  BSL_VAR__1->env[5] = BSL_VAR_arg5;
  BSL_VAR__1->env[6] = BSL_VAR_arg6;
  BSL_VAR__1->env[7] = BSL_VAR_arg7;
  BSL_VAR__1->env[8] = BSL_VAR_arg8;
  BSL_VAR__1->env[9] = BSL_VAR_arg9;
  BSL_VAR__1->env[10] = BSL_VAR_arg10;
  BSL_VAR__1->env[11] = BSL_VAR_arg11;
  BSL_VAR__1->env[12] = BSL_VAR_arg12;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_CON_15(BSL_RT_FUN_T fun, BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_VAR_arg2, BSL_RT_VAR_T BSL_VAR_arg3, BSL_RT_VAR_T BSL_VAR_arg4, BSL_RT_VAR_T BSL_VAR_arg5, BSL_RT_VAR_T BSL_VAR_arg6, BSL_RT_VAR_T BSL_VAR_arg7, BSL_RT_VAR_T BSL_VAR_arg8, BSL_RT_VAR_T BSL_VAR_arg9, BSL_RT_VAR_T BSL_VAR_arg10, BSL_RT_VAR_T BSL_VAR_arg11, BSL_RT_VAR_T BSL_VAR_arg12, BSL_RT_VAR_T BSL_VAR_arg13, BSL_RT_VAR_T BSL_VAR_arg14) {
  BSL_RT_CLOSURE_T BSL_VAR__1 = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 15 * sizeof(BSL_RT_VAR_T));
  BSL_VAR__1->fun = fun;
  BSL_VAR__1->env[0] = BSL_VAR_arg0;
  BSL_VAR__1->env[1] = BSL_VAR_arg1;
  BSL_VAR__1->env[2] = BSL_VAR_arg2;
  BSL_VAR__1->env[3] = BSL_VAR_arg3;
  BSL_VAR__1->env[4] = BSL_VAR_arg4;
  BSL_VAR__1->env[5] = BSL_VAR_arg5;
  BSL_VAR__1->env[6] = BSL_VAR_arg6;
  BSL_VAR__1->env[7] = BSL_VAR_arg7;
  BSL_VAR__1->env[8] = BSL_VAR_arg8;
  BSL_VAR__1->env[9] = BSL_VAR_arg9;
  BSL_VAR__1->env[10] = BSL_VAR_arg10;
  BSL_VAR__1->env[11] = BSL_VAR_arg11;
  BSL_VAR__1->env[12] = BSL_VAR_arg12;
  BSL_VAR__1->env[13] = BSL_VAR_arg13;
  BSL_VAR__1->env[14] = BSL_VAR_arg14;
  return (BSL_RT_VAR_T) BSL_VAR__1;
}
BSL_RT_VAR_T BSL_FUN_0(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_1(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_2(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_3(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_4(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_5(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_6(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_7(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_8(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_9(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_10(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_11(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_12(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_13(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_14(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_15(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_16(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_17(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_18(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_19(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_20(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_21(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_22(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_23(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_24(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_25(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_26(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_27(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_28(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_29(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_30(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_31(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_32(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_33(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_34(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_35(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_36(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_37(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_38(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_39(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_40(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_41(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_42(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_43(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_44(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_45(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_46(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_47(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_48(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_49(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_50(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_51(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_52(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_53(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_54(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_55(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_56(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_57(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_58(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_59(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_60(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_61(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_62(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_63(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_64(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_65(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_66(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_67(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_68(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_69(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_70(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_71(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_72(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_73(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_74(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_75(BSL_RT_VAR_T, BSL_RT_VAR_T[]);
BSL_RT_VAR_T BSL_FUN_0(BSL_RT_VAR_T BSL_VAR_Unit, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_1(BSL_FUN_1, BSL_VAR_Unit),  BSL_CON_Nothing() );
}
BSL_RT_VAR_T BSL_FUN_1(BSL_RT_VAR_T BSL_VAR_Nothing, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_2(BSL_FUN_2, BSL_VAR_Nothing, BSL_ENV[0]), BSL_CON_0(BSL_FUN_75));
}
BSL_RT_VAR_T BSL_FUN_2(BSL_RT_VAR_T BSL_VAR_Just, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_3(BSL_FUN_3, BSL_VAR_Just, BSL_ENV[0], BSL_ENV[1]), BSL_CON_0(BSL_FUN_73));
}
BSL_RT_VAR_T BSL_FUN_3(BSL_RT_VAR_T BSL_VAR_Cons, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_3(BSL_FUN_4, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2]),  BSL_CON_Nil() );
}
BSL_RT_VAR_T BSL_FUN_4(BSL_RT_VAR_T BSL_VAR_Nil, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_3(BSL_FUN_5, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2]), BSL_CON_0(BSL_FUN_71));
}
BSL_RT_VAR_T BSL_FUN_5(BSL_RT_VAR_T BSL_VAR_Write, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_4(BSL_FUN_6, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_VAR_Write), BSL_CON_0(BSL_FUN_70));
}
BSL_RT_VAR_T BSL_FUN_6(BSL_RT_VAR_T BSL_VAR_Read, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_5(BSL_FUN_7, BSL_ENV[0], BSL_ENV[1], BSL_VAR_Read, BSL_ENV[2], BSL_ENV[3]), BSL_CON_0(BSL_FUN_69));
}
BSL_RT_VAR_T BSL_FUN_7(BSL_RT_VAR_T BSL_VAR_Free, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_6(BSL_FUN_8, BSL_VAR_Free, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4]), BSL_CON_0(BSL_FUN_68));
}
BSL_RT_VAR_T BSL_FUN_8(BSL_RT_VAR_T BSL_VAR_Pure, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_7(BSL_FUN_9, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_VAR_Pure, BSL_ENV[3], BSL_ENV[4], BSL_ENV[5]), BSL_CON_0(BSL_FUN_65));
}
BSL_RT_VAR_T BSL_FUN_9(BSL_RT_VAR_T BSL_VAR_If, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_8(BSL_FUN_10, BSL_ENV[0], BSL_VAR_If, BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[5], BSL_ENV[6]), BSL_CON_0(BSL_FUN_63));
}
BSL_RT_VAR_T BSL_FUN_10(BSL_RT_VAR_T BSL_VAR_Eq, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_9(BSL_FUN_11, BSL_VAR_Eq, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[5], BSL_ENV[6], BSL_ENV[7]), BSL_CON_0(BSL_FUN_61));
}
BSL_RT_VAR_T BSL_FUN_11(BSL_RT_VAR_T BSL_VAR_Mul, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_9(BSL_FUN_12, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[5], BSL_ENV[6], BSL_ENV[7], BSL_ENV[8]), BSL_CON_0(BSL_FUN_59));
}
BSL_RT_VAR_T BSL_FUN_12(BSL_RT_VAR_T BSL_VAR_Add, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_10(BSL_FUN_13, BSL_VAR_Add, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[5], BSL_ENV[6], BSL_ENV[7], BSL_ENV[8]), BSL_CON_0(BSL_FUN_58));
}
BSL_RT_VAR_T BSL_FUN_13(BSL_RT_VAR_T BSL_VAR_B, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_10(BSL_FUN_14, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[5], BSL_ENV[6], BSL_ENV[7], BSL_ENV[8], BSL_ENV[9]), BSL_CON_0(BSL_FUN_57));
}
BSL_RT_VAR_T BSL_FUN_14(BSL_RT_VAR_T BSL_VAR_I, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_11(BSL_FUN_15, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_VAR_I, BSL_ENV[3], BSL_ENV[4], BSL_ENV[5], BSL_ENV[6], BSL_ENV[7], BSL_ENV[8], BSL_ENV[9]),  BSL_CON_True() );
}
BSL_RT_VAR_T BSL_FUN_15(BSL_RT_VAR_T BSL_VAR_True, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_12(BSL_FUN_16, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[5], BSL_ENV[6], BSL_ENV[7], BSL_ENV[8], BSL_VAR_True, BSL_ENV[9], BSL_ENV[10]),  BSL_CON_False() );
}
BSL_RT_VAR_T BSL_FUN_16(BSL_RT_VAR_T BSL_VAR_False, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_13(BSL_FUN_17, BSL_ENV[0], BSL_ENV[1], BSL_VAR_False, BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[5], BSL_ENV[6], BSL_ENV[7], BSL_ENV[8], BSL_ENV[9], BSL_ENV[10], BSL_ENV[11]), BSL_CON_2(BSL_FUN_53, BSL_ENV[8], BSL_ENV[11]));
}
BSL_RT_VAR_T BSL_FUN_17(BSL_RT_VAR_T BSL_VAR_fmap, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_13(BSL_FUN_18, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[5], BSL_ENV[6], BSL_ENV[7], BSL_ENV[9], BSL_ENV[10], BSL_ENV[11], BSL_ENV[12], BSL_VAR_fmap), BSL_ENV[8]);
}
BSL_RT_VAR_T BSL_FUN_18(BSL_RT_VAR_T BSL_VAR_return, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_15(BSL_FUN_19, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[5], BSL_ENV[6], BSL_ENV[7], BSL_ENV[8], BSL_ENV[9], BSL_ENV[10], BSL_ENV[11], NULL, BSL_ENV[12], BSL_VAR_return), NULL);
}
BSL_RT_VAR_T BSL_FUN_19(BSL_RT_VAR_T _, BSL_RT_VAR_T BSL_ENV[]) {
  BSL_ENV[12] = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 3 * sizeof(BSL_RT_VAR_T));
  memcpy(BSL_ENV[12], BSL_CON_3(BSL_FUN_20, BSL_ENV[3], BSL_ENV[12], BSL_ENV[13]), sizeof(BSL_RT_FUN_T) + 3 * sizeof(BSL_RT_VAR_T));
  return BSL_RT_CALL(BSL_CON_12(BSL_FUN_24, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[5], BSL_ENV[6], BSL_ENV[7], BSL_ENV[9], BSL_ENV[10], BSL_ENV[11], BSL_ENV[14]), BSL_RT_CALL(BSL_ENV[3],BSL_RT_CALL(BSL_ENV[8],BSL_CON_1(BSL_FUN_52, BSL_ENV[14]))));
}
BSL_RT_VAR_T BSL_FUN_20(BSL_RT_VAR_T BSL_VAR_x, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_CON_4(BSL_FUN_21, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_VAR_x);
}
BSL_RT_VAR_T BSL_FUN_21(BSL_RT_VAR_T BSL_VAR_f, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_RT_CALL(BSL_CON_4(BSL_FUN_22, BSL_ENV[0], BSL_ENV[1], BSL_VAR_f, BSL_ENV[2]), BSL_ENV[3]);
}
BSL_RT_VAR_T BSL_FUN_22(BSL_RT_VAR_T BSL_VAR__1, BSL_RT_VAR_T BSL_ENV[]) {
  switch (((BSL_TYPE_IO*)(BSL_VAR__1))->T) {
    case BSL_TAG_Pure: {
      BSL_RT_VAR_T BSL_VAR_x = ((BSL_TYPE_IO*)(BSL_VAR__1))->arg0;
      return BSL_RT_CALL(BSL_ENV[2],BSL_VAR_x);
    }
    case BSL_TAG_Free: {
      BSL_RT_VAR_T BSL_VAR_x = ((BSL_TYPE_IO*)(BSL_VAR__1))->arg0;
      return BSL_RT_CALL(BSL_ENV[0],BSL_RT_CALL(BSL_RT_CALL(BSL_ENV[3],BSL_CON_2(BSL_FUN_23, BSL_ENV[1], BSL_ENV[2])),BSL_VAR_x));
    }
  }
}
BSL_RT_VAR_T BSL_FUN_23(BSL_RT_VAR_T BSL_VAR_y, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_RT_CALL(BSL_RT_CALL(BSL_ENV[0],BSL_VAR_y),BSL_ENV[1]);
}
BSL_RT_VAR_T BSL_FUN_24(BSL_RT_VAR_T BSL_VAR_getInt, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_9(BSL_FUN_25, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[4], BSL_ENV[5], BSL_ENV[6], BSL_ENV[7], BSL_ENV[8], BSL_ENV[9]), BSL_CON_4(BSL_FUN_51, BSL_ENV[3], BSL_ENV[9], BSL_ENV[10], BSL_ENV[11]));
}
BSL_RT_VAR_T BSL_FUN_25(BSL_RT_VAR_T BSL_VAR_putInt, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_11(BSL_FUN_26, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[5], BSL_ENV[6], BSL_ENV[7], BSL_ENV[8], BSL_VAR_putInt, NULL), NULL);
}
BSL_RT_VAR_T BSL_FUN_26(BSL_RT_VAR_T _, BSL_RT_VAR_T BSL_ENV[]) {
  BSL_ENV[10] = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 4 * sizeof(BSL_RT_VAR_T));
  memcpy(BSL_ENV[10], BSL_CON_4(BSL_FUN_27, BSL_ENV[5], BSL_ENV[6], BSL_ENV[8], BSL_ENV[10]), sizeof(BSL_RT_FUN_T) + 4 * sizeof(BSL_RT_VAR_T));
  return BSL_RT_CALL(BSL_CON_8(BSL_FUN_33, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[7], BSL_ENV[9], BSL_ENV[10]), BSL_CON_0(BSL_FUN_49));
}
BSL_RT_VAR_T BSL_FUN_27(BSL_RT_VAR_T BSL_VAR_x, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_RT_CALL(BSL_CON_4(BSL_FUN_28, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3]), BSL_VAR_x);
}
BSL_RT_VAR_T BSL_FUN_28(BSL_RT_VAR_T BSL_VAR__1, BSL_RT_VAR_T BSL_ENV[]) {
  switch (((BSL_TYPE_IO*)(BSL_VAR__1))->T) {
    case BSL_TAG_Pure: {
      BSL_RT_VAR_T BSL_VAR_x = ((BSL_TYPE_IO*)(BSL_VAR__1))->arg0;
      return BSL_VAR_x;
    }
    case BSL_TAG_Free: {
      BSL_RT_VAR_T BSL_VAR_x = ((BSL_TYPE_IO*)(BSL_VAR__1))->arg0;
      return BSL_RT_CALL(BSL_CON_4(BSL_FUN_29, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3]), BSL_VAR_x);
    }
  }
}
BSL_RT_VAR_T BSL_FUN_29(BSL_RT_VAR_T BSL_VAR__1, BSL_RT_VAR_T BSL_ENV[]) {
  switch (((BSL_TYPE_IOImpl*)(BSL_VAR__1))->T) {
    case BSL_TAG_Write: {
      BSL_RT_VAR_T BSL_VAR_c = ((BSL_TYPE_IOImpl*)(BSL_VAR__1))->arg0;
      BSL_RT_VAR_T BSL_VAR_x = ((BSL_TYPE_IOImpl*)(BSL_VAR__1))->arg1;
      return BSL_RT_CALL(BSL_CON_2(BSL_FUN_30, BSL_ENV[3], BSL_VAR_x),  (printf("%d\n", (int) BSL_VAR_c), NULL) );
    }
    case BSL_TAG_Read: {
      BSL_RT_VAR_T BSL_VAR_g = ((BSL_TYPE_IOImpl*)(BSL_VAR__1))->arg0;
      return BSL_RT_CALL(BSL_CON_3(BSL_FUN_31, BSL_ENV[2], BSL_VAR_g, BSL_ENV[3]), BSL_CON_2(BSL_FUN_32, BSL_ENV[0], BSL_ENV[1]));
    }
  }
}
BSL_RT_VAR_T BSL_FUN_30(BSL_RT_VAR_T BSL_VAR___, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_ENV[0],BSL_ENV[1]);
}
BSL_RT_VAR_T BSL_FUN_31(BSL_RT_VAR_T BSL_VAR_x, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_ENV[2],BSL_RT_CALL(BSL_ENV[1],BSL_RT_CALL(BSL_VAR_x,BSL_ENV[0])));
}
BSL_RT_VAR_T BSL_FUN_32(BSL_RT_VAR_T BSL_VAR_x, BSL_RT_VAR_T BSL_ENV[]) {
 return  (scanf("%d",&BSL_VAR_x) == 1 ? BSL_RT_CALL(BSL_ENV[0], BSL_VAR_x) : BSL_ENV[1]) ;
}
BSL_RT_VAR_T BSL_FUN_33(BSL_RT_VAR_T BSL_VAR_add, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_9(BSL_FUN_34, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[5], BSL_VAR_add, BSL_ENV[6], BSL_ENV[7]), BSL_CON_0(BSL_FUN_47));
}
BSL_RT_VAR_T BSL_FUN_34(BSL_RT_VAR_T BSL_VAR_mul, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_8(BSL_FUN_35, BSL_ENV[0], BSL_ENV[1], BSL_ENV[3], BSL_ENV[4], BSL_ENV[6], BSL_VAR_mul, BSL_ENV[7], BSL_ENV[8]), BSL_CON_2(BSL_FUN_45, BSL_ENV[2], BSL_ENV[5]));
}
BSL_RT_VAR_T BSL_FUN_35(BSL_RT_VAR_T BSL_VAR_eq, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_10(BSL_FUN_36, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_VAR_eq, NULL, BSL_ENV[5], BSL_ENV[6], BSL_ENV[7]), NULL);
}
BSL_RT_VAR_T BSL_FUN_36(BSL_RT_VAR_T _, BSL_RT_VAR_T BSL_ENV[]) {
  BSL_ENV[6] = BSL_RT_MALLOC(sizeof(BSL_RT_FUN_T) + 4 * sizeof(BSL_RT_VAR_T));
  memcpy(BSL_ENV[6], BSL_CON_4(BSL_FUN_37, BSL_ENV[4], BSL_ENV[5], BSL_ENV[6], BSL_ENV[7]), sizeof(BSL_RT_FUN_T) + 4 * sizeof(BSL_RT_VAR_T));
  return BSL_RT_CALL(BSL_CON_7(BSL_FUN_40, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[6], BSL_ENV[8], BSL_ENV[9]),  1 );
}
BSL_RT_VAR_T BSL_FUN_37(BSL_RT_VAR_T BSL_VAR_x, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_RT_CALL(BSL_CON_4(BSL_FUN_38, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3]), BSL_VAR_x);
}
BSL_RT_VAR_T BSL_FUN_38(BSL_RT_VAR_T BSL_VAR__1, BSL_RT_VAR_T BSL_ENV[]) {
  switch (((BSL_TYPE_Expr*)(BSL_VAR__1))->T) {
    case BSL_TAG_I: {
      BSL_RT_VAR_T BSL_VAR_n = ((BSL_TYPE_Expr*)(BSL_VAR__1))->arg0;
      return BSL_VAR_n;
    }
    case BSL_TAG_B: {
      BSL_RT_VAR_T BSL_VAR_b = ((BSL_TYPE_Expr*)(BSL_VAR__1))->arg0;
      return BSL_VAR_b;
    }
    case BSL_TAG_Add: {
      BSL_RT_VAR_T BSL_VAR_e1 = ((BSL_TYPE_Expr*)(BSL_VAR__1))->arg0;
      BSL_RT_VAR_T BSL_VAR_e2 = ((BSL_TYPE_Expr*)(BSL_VAR__1))->arg1;
      return BSL_RT_CALL(BSL_RT_CALL(BSL_ENV[0],BSL_RT_CALL(BSL_ENV[2],BSL_VAR_e1)),BSL_RT_CALL(BSL_ENV[2],BSL_VAR_e2));
    }
    case BSL_TAG_Mul: {
      BSL_RT_VAR_T BSL_VAR_e1 = ((BSL_TYPE_Expr*)(BSL_VAR__1))->arg0;
      BSL_RT_VAR_T BSL_VAR_e2 = ((BSL_TYPE_Expr*)(BSL_VAR__1))->arg1;
      return BSL_RT_CALL(BSL_RT_CALL(BSL_ENV[3],BSL_RT_CALL(BSL_ENV[2],BSL_VAR_e1)),BSL_RT_CALL(BSL_ENV[2],BSL_VAR_e2));
    }
    case BSL_TAG_Eq: {
      BSL_RT_VAR_T BSL_VAR_e1 = ((BSL_TYPE_Expr*)(BSL_VAR__1))->arg0;
      BSL_RT_VAR_T BSL_VAR_e2 = ((BSL_TYPE_Expr*)(BSL_VAR__1))->arg1;
      return BSL_RT_CALL(BSL_RT_CALL(BSL_ENV[1],BSL_RT_CALL(BSL_ENV[2],BSL_VAR_e1)),BSL_RT_CALL(BSL_ENV[2],BSL_VAR_e2));
    }
    case BSL_TAG_If: {
      BSL_RT_VAR_T BSL_VAR_c = ((BSL_TYPE_Expr*)(BSL_VAR__1))->arg0;
      BSL_RT_VAR_T BSL_VAR_e1 = ((BSL_TYPE_Expr*)(BSL_VAR__1))->arg1;
      BSL_RT_VAR_T BSL_VAR_e2 = ((BSL_TYPE_Expr*)(BSL_VAR__1))->arg2;
      return BSL_RT_CALL(BSL_CON_3(BSL_FUN_39, BSL_VAR_e1, BSL_VAR_e2, BSL_ENV[2]), BSL_RT_CALL(BSL_ENV[2],BSL_VAR_c));
    }
  }
}
BSL_RT_VAR_T BSL_FUN_39(BSL_RT_VAR_T BSL_VAR__1, BSL_RT_VAR_T BSL_ENV[]) {
  switch (((BSL_TYPE_Bool*)(BSL_VAR__1))->T) {
    case BSL_TAG_True: {
      return BSL_RT_CALL(BSL_ENV[2],BSL_ENV[0]);
    }
    case BSL_TAG_False: {
      return BSL_RT_CALL(BSL_ENV[2],BSL_ENV[1]);
    }
  }
}
BSL_RT_VAR_T BSL_FUN_40(BSL_RT_VAR_T BSL_VAR_one, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_8(BSL_FUN_41, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_VAR_one, BSL_ENV[5], BSL_ENV[6]),  2 );
}
BSL_RT_VAR_T BSL_FUN_41(BSL_RT_VAR_T BSL_VAR_two, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_8(BSL_FUN_42, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2], BSL_ENV[3], BSL_ENV[4], BSL_ENV[6], BSL_ENV[7], BSL_VAR_two), BSL_RT_CALL(BSL_ENV[2],BSL_ENV[5]));
}
BSL_RT_VAR_T BSL_FUN_42(BSL_RT_VAR_T BSL_VAR_one, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_7(BSL_FUN_43, BSL_ENV[0], BSL_ENV[1], BSL_ENV[3], BSL_ENV[4], BSL_VAR_one, BSL_ENV[5], BSL_ENV[6]), BSL_RT_CALL(BSL_ENV[2],BSL_ENV[7]));
}
BSL_RT_VAR_T BSL_FUN_43(BSL_RT_VAR_T BSL_VAR_two, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_CON_1(BSL_FUN_44, BSL_ENV[6]), BSL_RT_CALL(BSL_ENV[5],BSL_RT_CALL(BSL_ENV[3],BSL_RT_CALL(BSL_RT_CALL(BSL_RT_CALL(BSL_ENV[2],BSL_RT_CALL(BSL_RT_CALL(BSL_ENV[1],BSL_RT_CALL(BSL_RT_CALL(BSL_ENV[0],BSL_ENV[4]),BSL_ENV[4])),BSL_VAR_two)),BSL_ENV[4]),BSL_VAR_two))));
}
BSL_RT_VAR_T BSL_FUN_44(BSL_RT_VAR_T BSL_VAR_main, BSL_RT_VAR_T BSL_ENV[]) {
  return BSL_RT_CALL(BSL_ENV[0],BSL_VAR_main);
}
BSL_RT_VAR_T BSL_FUN_45(BSL_RT_VAR_T BSL_VAR_a, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_CON_3(BSL_FUN_46, BSL_ENV[0], BSL_ENV[1], BSL_VAR_a);
}
BSL_RT_VAR_T BSL_FUN_46(BSL_RT_VAR_T BSL_VAR_b, BSL_RT_VAR_T BSL_ENV[]) {
 return  ((((int) BSL_ENV[2]) == ((int) BSL_VAR_b)) ? BSL_ENV[1] : BSL_ENV[0]) ;
}
BSL_RT_VAR_T BSL_FUN_47(BSL_RT_VAR_T BSL_VAR_a, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_CON_1(BSL_FUN_48, BSL_VAR_a);
}
BSL_RT_VAR_T BSL_FUN_48(BSL_RT_VAR_T BSL_VAR_b, BSL_RT_VAR_T BSL_ENV[]) {
 return  ((int) BSL_ENV[0]) * ((int) BSL_VAR_b) ;
}
BSL_RT_VAR_T BSL_FUN_49(BSL_RT_VAR_T BSL_VAR_a, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_CON_1(BSL_FUN_50, BSL_VAR_a);
}
BSL_RT_VAR_T BSL_FUN_50(BSL_RT_VAR_T BSL_VAR_b, BSL_RT_VAR_T BSL_ENV[]) {
 return  ((int) BSL_ENV[0]) + ((int) BSL_VAR_b) ;
}
BSL_RT_VAR_T BSL_FUN_51(BSL_RT_VAR_T BSL_VAR_x, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_RT_CALL(BSL_ENV[0],BSL_RT_CALL(BSL_RT_CALL(BSL_ENV[2],BSL_VAR_x),BSL_RT_CALL(BSL_ENV[3],BSL_ENV[1])));
}
BSL_RT_VAR_T BSL_FUN_52(BSL_RT_VAR_T BSL_VAR_x, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_RT_CALL(BSL_ENV[0],BSL_VAR_x);
}
BSL_RT_VAR_T BSL_FUN_53(BSL_RT_VAR_T BSL_VAR_f, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_CON_3(BSL_FUN_54, BSL_ENV[0], BSL_ENV[1], BSL_VAR_f);
}
BSL_RT_VAR_T BSL_FUN_54(BSL_RT_VAR_T BSL_VAR_x, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_RT_CALL(BSL_CON_3(BSL_FUN_55, BSL_ENV[0], BSL_ENV[1], BSL_ENV[2]), BSL_VAR_x);
}
BSL_RT_VAR_T BSL_FUN_55(BSL_RT_VAR_T BSL_VAR__1, BSL_RT_VAR_T BSL_ENV[]) {
  switch (((BSL_TYPE_IOImpl*)(BSL_VAR__1))->T) {
    case BSL_TAG_Write: {
      BSL_RT_VAR_T BSL_VAR_s = ((BSL_TYPE_IOImpl*)(BSL_VAR__1))->arg0;
      BSL_RT_VAR_T BSL_VAR_k = ((BSL_TYPE_IOImpl*)(BSL_VAR__1))->arg1;
      return BSL_RT_CALL(BSL_RT_CALL(BSL_ENV[1],BSL_VAR_s),BSL_RT_CALL(BSL_ENV[2],BSL_VAR_k));
    }
    case BSL_TAG_Read: {
      BSL_RT_VAR_T BSL_VAR_k = ((BSL_TYPE_IOImpl*)(BSL_VAR__1))->arg0;
      return BSL_RT_CALL(BSL_ENV[0],BSL_CON_2(BSL_FUN_56, BSL_ENV[2], BSL_VAR_k));
    }
  }
}
BSL_RT_VAR_T BSL_FUN_56(BSL_RT_VAR_T BSL_VAR_s, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_RT_CALL(BSL_ENV[0],BSL_RT_CALL(BSL_ENV[1],BSL_VAR_s));
}
BSL_RT_VAR_T BSL_FUN_57(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_ENV[]) {
 return  BSL_CON_I(BSL_VAR_arg0) ;
}
BSL_RT_VAR_T BSL_FUN_58(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_ENV[]) {
 return  BSL_CON_B(BSL_VAR_arg0) ;
}
BSL_RT_VAR_T BSL_FUN_59(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_CON_1(BSL_FUN_60, BSL_VAR_arg0);
}
BSL_RT_VAR_T BSL_FUN_60(BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_ENV[]) {
 return  BSL_CON_Add(BSL_ENV[0], BSL_VAR_arg1) ;
}
BSL_RT_VAR_T BSL_FUN_61(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_CON_1(BSL_FUN_62, BSL_VAR_arg0);
}
BSL_RT_VAR_T BSL_FUN_62(BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_ENV[]) {
 return  BSL_CON_Mul(BSL_ENV[0], BSL_VAR_arg1) ;
}
BSL_RT_VAR_T BSL_FUN_63(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_CON_1(BSL_FUN_64, BSL_VAR_arg0);
}
BSL_RT_VAR_T BSL_FUN_64(BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_ENV[]) {
 return  BSL_CON_Eq(BSL_ENV[0], BSL_VAR_arg1) ;
}
BSL_RT_VAR_T BSL_FUN_65(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_CON_1(BSL_FUN_66, BSL_VAR_arg0);
}
BSL_RT_VAR_T BSL_FUN_66(BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_CON_2(BSL_FUN_67, BSL_ENV[0], BSL_VAR_arg1);
}
BSL_RT_VAR_T BSL_FUN_67(BSL_RT_VAR_T BSL_VAR_arg2, BSL_RT_VAR_T BSL_ENV[]) {
 return  BSL_CON_If(BSL_ENV[0], BSL_ENV[1], BSL_VAR_arg2) ;
}
BSL_RT_VAR_T BSL_FUN_68(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_ENV[]) {
 return  BSL_CON_Pure(BSL_VAR_arg0) ;
}
BSL_RT_VAR_T BSL_FUN_69(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_ENV[]) {
 return  BSL_CON_Free(BSL_VAR_arg0) ;
}
BSL_RT_VAR_T BSL_FUN_70(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_ENV[]) {
 return  BSL_CON_Read(BSL_VAR_arg0) ;
}
BSL_RT_VAR_T BSL_FUN_71(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_CON_1(BSL_FUN_72, BSL_VAR_arg0);
}
BSL_RT_VAR_T BSL_FUN_72(BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_ENV[]) {
 return  BSL_CON_Write(BSL_ENV[0], BSL_VAR_arg1) ;
}
BSL_RT_VAR_T BSL_FUN_73(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_ENV[]) {
 return BSL_CON_1(BSL_FUN_74, BSL_VAR_arg0);
}
BSL_RT_VAR_T BSL_FUN_74(BSL_RT_VAR_T BSL_VAR_arg1, BSL_RT_VAR_T BSL_ENV[]) {
 return  BSL_CON_Cons(BSL_ENV[0], BSL_VAR_arg1) ;
}
BSL_RT_VAR_T BSL_FUN_75(BSL_RT_VAR_T BSL_VAR_arg0, BSL_RT_VAR_T BSL_ENV[]) {
 return  BSL_CON_Just(BSL_VAR_arg0) ;
}
int main() { BSL_RT_CALL(BSL_CON_0(BSL_FUN_0),  BSL_CON_Unit() ); }
