#!/bin/bash
script=`dirname \`realpath $0\``
g++ -std=c++11 -Wall $script/../src/main.cpp -o $script/bsl-compiler &&
$script/bsl-compiler $1 >$1.c &&
(if [ -z "$BSL_RT_WITH_GC" ];
then gcc -w -I$script/../rt/ -O3 $1.c -o $1.out;
else gcc -w -lgc -I$script/../rt/with_gc -O3 $1.c -o $1.out;
fi) &&
$1.out
rm $script/bsl-compiler 2>/dev/null &&
rm $1.c 2>/dev/null&&
rm $1.out 2>/dev/null

